version: 2.1

orbs:
  node: circleci/node@5

jobs:
  node-test: &node-test
    docker:
      - image: node
    steps:
      - checkout
      - run: node --version
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
  node14-test:
    <<: *node-test
    docker:
      - image: node:14
  node16-test:
    <<: *node-test
    docker:
      - image: node:16
  node18-test:
    <<: *node-test
    docker:
      - image: node:18
  node20-test:
    <<: *node-test
    docker:
      - image: node:20

workflows:
  multiple-node-test:
    jobs:
      - node14-test
      - node16-test
      - node18-test
      - node20-test