version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  node14-test:
    docker:
      - image: cimg/node:14.21
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: node --version
      - run:
          name: Run tests
          command: npm test

  node16-test:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: node --version
      - run:
          name: Run tests
          command: npm test

workflows:
  multiple-node-test:
    jobs:
      - node14-test
      - node16-test